### ISSUE TITLE
Run all inventory reports and export to CSV

### ISSUE THREAD

**Issue by thetootall** [EntropicTech/HyperVReports#23]
Any way to export these reports similarly to VMWare and their RVtools exports? 

The individual reports provide great info, but it only (1) prints the results to the screen, and (2) theres no way to export to CSV (leaving a lot of cleanup)

[1]  VM vCPU and RAM
[2]  VM Networking
[3]  VM VHDX Size/Location/Type

**Comment by EntropicTech** [comment]
Hey, so this is a tool I wrote when I was working as an engineer on Rackspace's Hyper-V team, so most of the tools are written in a way to provide text you can paste into a ticket to show a customer. Some of the team did occasionally need it as CSV, so I added it as a feature, but I never incorporated it into the ASCII menu. If you run the function directly you can use the -ExportToCSV parameter and supply it a path to get the report in CSV format.

Here are the notes in the code for the function:

function Get-HyperVVMInfo

        .SYNOPSIS
            Get-HyperVVMInfo collects Hyper-V VM info and prints report of their data.       
        
        .PARAMETER ExportToCSV
            Exports the report to specified .CSV in path.       
        
        .EXAMPLE
            C:\PS> Get-HyperVVMInfo -ExportToCSV C:\rs-pkgs\VMInfo.csv


Hope that helps!
